spring:
  jackson:
    time-zone: Asia/Seoul
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      ssl:
        enabled: true

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            redirect-uri: ${REDIRECT_URL}
            authorization-grant-type: authorization_code
            scope:
                     - account_email
                     - name
                     - gender
                     - birthday
                     - birthyear
                     - phone_number
            client-name: Kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

Authorization:
  header: "Authorization"

secret: ${SECRET}

cloud:
  aws:
    credentials:
      accessKey: ${AWS_ACCESS_KEY}
      secretKey: ${AWS_SECRET_KEY}
    region:
      static: ap-northeast-2
    sqs:
      queue:
        name: ${AWS_SQS_QUEUE_NAME}
    s3:
      bucket: ${AWS_S3_BUCKET}
    sns:
      region: ap-northeast-1

springdoc:
  override-with-generic-response: false

grpc:
  client:
    userRecommendationService:
      address: "static://recommend:50051"
      negotiationType: plaintext
  server:
    host: localhost


openai:
  model: gpt-4o
  url: "https://api.openai.com/v1/chat/completions"
  secret-key: ${GPT_KEY}
